In [4]:
import numpy as np

#Create 1D Array

In [ ]:
arr1=np.array([1,2,3,4])

In [8]:
arr1.size

4

In [15]:
type(arr1)

numpy.ndarray

## Create 2D array

In [18]:
arr2=np.array([[1,2,3],
              [4,5,6]])


In [19]:
arr2.shape


(2, 3)

In [20]:
arr2.size


6

In [21]:
type(arr2)

numpy.ndarray

## Create 3D Array

In [34]:
arr3=np.array([[[1,2,3],[1,2,3]],[[1,3,4],[2,3,4]],[[1,2,3],[2,3,4]]])

In [35]:
arr3

array([[[1, 2, 3],
        [1, 2, 3]],

       [[1, 3, 4],
        [2, 3, 4]],

       [[1, 2, 3],
        [2, 3, 4]]])

In [36]:
arr3.shape


(3, 2, 3)

In [37]:
arr3.ndim


3

In [38]:
arr3.size

18

In [39]:
type(arr3)

numpy.ndarray

In [40]:
arr3[0,0,2]

np.int64(3)

In [41]:
arr3.dtype

dtype('int64')

In [42]:
arr3[2,1,1]

np.int64(3)

In [44]:
arr3[1:3]

array([[[1, 3, 4],
        [2, 3, 4]],

       [[1, 2, 3],
        [2, 3, 4]]])

In [46]:
arr3[:-1]

array([[[1, 2, 3],
        [1, 2, 3]],

       [[1, 3, 4],
        [2, 3, 4]]])

In [140]:
zero=np.zeros((2,2,3))
zero

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [147]:
full = np.full((2,2,3),2)

In [67]:
full

array([[[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]],

       [[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]]])

In [69]:
full.ndim

3

In [74]:
arr4=np.random.rand(2,1,1)
arr4

array([[[0.84340797]],

       [[0.96064993]]])

In [75]:
arr4.ndim

3

# Update & Delete

In [78]:
full[0,0,2]=5

In [79]:
full


array([[[2, 2, 5],
        [2, 2, 2],
        [2, 2, 2]],

       [[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]]])

In [82]:
del full

In [121]:
full=np.full((2,3,4),3)

In [86]:
a1=np.random.rand(2,2,3)

In [87]:
a1


array([[[0.13287767, 0.40377235, 0.83648112],
        [0.53574681, 0.24333879, 0.95414743]],

       [[0.55184947, 0.47137076, 0.23768093],
        [0.86454428, 0.25284022, 0.95690601]]])

In [89]:
a1[0,0,1]=1

In [93]:
a2=np.random.rand(2,2,3)

In [96]:
np.add(a1,a2)

array([[[0.81781563, 1.4318334 , 1.82466363],
        [1.51505033, 0.83727088, 1.3857304 ]],

       [[1.0517807 , 0.59139851, 0.66751584],
        [0.95234971, 0.36159351, 0.96230288]]])

In [97]:
np.multiply(a1,a2)

array([[[0.09101296, 0.4318334 , 0.82659601],
        [0.52465874, 0.14452672, 0.41179378]],

       [[0.27588678, 0.05657757, 0.10216356],
        [0.07591169, 0.0274972 , 0.0051643 ]]])

In [98]:
np.divide(a1,a2)

array([[[  0.19399956,   2.31570788,   0.84648444],
        [  0.54706921,   0.4097081 ,   2.21080878]],

       [[  1.10385077,   3.92718142,   0.55295865],
        [  9.84613616,   2.32489735, 177.30759697]]])

##Apending and insert

In [153]:
arr=np.append(full,zero,axis=1)

In [124]:
full.ndim

3

In [125]:
zero.ndim

3

In [137]:
full.size

24

In [127]:
full.size

24

In [139]:
zero.size

18

In [142]:
zero=zero.reshape(2,2,3)

In [152]:
inserted_array=np.insert(zero,0,full,axis=0)
inserted_array

array([[[2., 2., 2.],
        [2., 2., 2.]],

       [[2., 2., 2.],
        [2., 2., 2.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [144]:
zero.shape

(2, 2, 3)

In [145]:
full.shape

(2, 3, 4)

In [148]:
full=full.reshape(2,2,3)

In [149]:
full.shape

(2, 2, 3)

In [150]:
zero.shape

(2, 2, 3)

In [154]:
arr

array([[[2., 2., 2.],
        [2., 2., 2.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[2., 2., 2.],
        [2., 2., 2.],
        [0., 0., 0.],
        [0., 0., 0.]]])